version: '3'

services:
  nginx:
    container_name: backend_staging_web_server
    restart: always
    image: nginx
    volumes:
    - ./build-scripts/nginx/stage/default.conf:/etc/nginx/conf.d/default.conf
    ports:
     - 7000:80
    depends_on:
      - web
  web:
    build: .
    image: backend:1.0
    restart: always
    container_name: backend_staging_app_server
    command: gunicorn demo_project.wsgi:application --env DJANGO_SETTINGS_MODULE=demo_project.settings.stage --bind 0.0.0.0:4000
    volumes:
      - .:/code
    ports:
      - 4000
    depends_on:
      - db
  db:
    container_name: backend_staging_db_server
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 3306
    environment:
      MYSQL_ROOT_PASSWORD: stride123
    volumes:
      - backend_db_stage_volume:/var/lib/mysql

volumes:
  backend_db_stage_volume: