version: '3'

services:
  web:
    build: .
    image: backend:1.0
    container_name: backend_staging
    command: gunicorn demo_project.wsgi:application --env DJANGO_SETTINGS_MODULE=demo_project.settings.stage --bind 0.0.0.0:7000
    volumes:
      - .:/code
    ports:
      - 7000:7000
    env_file:
      - .staging-env
    network_mode: "host"